apiVersion: lansweeper.com/v1alpha1
kind: Repository
metadata:
  annotations:
    github.com/project-slug: Lansweeper/ClikchouseBenchTool
  description: Benchmarking tool for clickhouse queries
  name: ClikchouseBenchTool
spec:
  lifecycle: stable
  owner: user:juancarlosllhL